# Generated by Django 4.1 on 2022-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskregister',
            name='mitigation_actions',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskregister',
            name='oversight_responsibility',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskregister',
            name='risk_category',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
