# Generated by Django 4.1 on 2022-11-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0002_riskregister_mitigation_actions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskregister',
            old_name='impact_area',
            new_name='control_form',
        ),
        migrations.RenameField(
            model_name='riskregister',
            old_name='oversight_responsibility',
            new_name='key_risk_drivers',
        ),
        migrations.RenameField(
            model_name='riskregister',
            old_name='key_controls',
            new_name='risk_impact_area',
        ),
        migrations.RemoveField(
            model_name='riskregister',
            name='key_drivers_of_impact',
        ),
        migrations.RemoveField(
            model_name='riskregister',
            name='risk_category',
        ),
    ]
